---
- name: Install ufw.
  become: yes
  apt:
    name: ufw
    state: latest

- name: Allow SSH access to logserver.
  ufw:
    rule: allow
    proto: tcp
    from_ip: any
    port: 22
  notify: restart ufw

- name: Allow access to Kibana web interface from anywhere.
  ufw:
    rule: allow
    proto: tcp
    from_ip: any
    port: "{{ item }}"
  notify: restart ufw
  with_items:
    - 80
    - 443

- name: Restrict access to Logstash service to logclients.
  ufw:
    rule: allow
    proto: tcp
    from_ip: "{{ hostvars[item]['inventory_hostname'] }}"
    port: 5000
  notify: restart ufw
  with_items: "{{groups.logclients}}"
  # Using conditional to avoid undefined failure if facts haven't been gathered from logclients.
  # Ansible v2 interprets args to `with_items` dynamically, which introduces the error.
  # Make sure to include a gather_facts play on all logclients prior to running this role.
  #  when: hostvars[item]['ansible_'+elk_network_interface] is defined

- name: Start ufw service.
  service:
    name: ufw
    state: started
    enabled: yes

- name: Enable ufw functionality.
  ufw:
    state: enabled
